-- Run this file once in the Supabase SQL Editor.

create table if not exists public.topics (
    id bigint generated by default as identity primary key,
    topic text not null unique,
    used boolean not null default false,
    last_used timestamptz
);

create table if not exists public.attempts (
    id bigint generated by default as identity primary key,
    topic_id bigint not null references public.topics(id),
    paragraph_type text not null,
    score integer not null check (score between 1 and 6),
    grammar integer not null check (grammar between 1 and 6),
    vocabulary integer not null check (vocabulary between 1 and 6),
    structure integer not null check (structure between 1 and 6),
    argument_quality integer not null check (argument_quality between 1 and 6),
    created_at timestamptz not null default now()
);

create index if not exists attempts_created_at_idx
    on public.attempts (created_at);

-- The API uses a server-side database connection. Keep direct browser access
-- blocked unless explicit Supabase API policies are added later.
alter table public.topics enable row level security;
alter table public.attempts enable row level security;
